# Generated by Django 5.0.6 on 2024-10-06 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YoutubeVideoSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=32, unique=True)),
                ('summary', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=256)),
                ('experience_code', models.IntegerField(choices=[(1, 'I am completely new'), (2, 'I know some basics'), (3, 'Worked in the past but need to refresh')])),
                ('dedication_code', models.IntegerField(choices=[(1, 'I want to learn casually at my own pace'), (2, 'I am busy but I have dedicated time for learning'), (3, 'I am a full time learner')])),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('subject_name', 'experience_code', 'dedication_code')},
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=256)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='explore.subject')),
            ],
        ),
        migrations.CreateModel(
            name='YoutubeVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_key', models.CharField(max_length=32)),
                ('video_title', models.CharField(max_length=256)),
                ('likes_count', models.IntegerField(null=True)),
                ('views_count', models.IntegerField(null=True)),
                ('uploaded_on', models.DateField(null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='explore.topic')),
            ],
        ),
    ]
