# Generated by Django 5.0.6 on 2024-10-12 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='topics_created',
            field=models.BooleanField(default=False),
        ),
    ]
