# Generated by Django 5.0.6 on 2024-09-30 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0002_topic_created_on_alter_topic_subject_youtubevideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
