# Generated by Django 5.0.6 on 2024-10-02 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0003_alter_subject_created_on_alter_topic_created_on_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='youtubevideo',
            name='channel_name',
        ),
        migrations.RemoveField(
            model_name='youtubevideo',
            name='video_url',
        ),
        migrations.AddField(
            model_name='youtubevideo',
            name='likes_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='youtubevideo',
            name='uploaded_on',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='youtubevideo',
            name='video_key',
            field=models.CharField(default='None', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='youtubevideo',
            name='views_count',
            field=models.IntegerField(null=True),
        ),
    ]
