# Generated by Django 5.0.6 on 2024-10-12 19:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0003_subject_tracking_id'),
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usersubject',
            unique_together={('user', 'subject')},
        ),
        migrations.AlterUniqueTogether(
            name='usertopic',
            unique_together={('user', 'topic')},
        ),
    ]
