# Generated by Django 5.0.6 on 2024-10-02 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_usersubject_created_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertopic',
            name='course_find_status',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
