# Generated by Django 5.0.6 on 2024-10-02 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_usertopic_course_find_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubject',
            name='status',
            field=models.CharField(default='PROCESSING', max_length=32),
        ),
        migrations.AddField(
            model_name='usersubject',
            name='tracking_id',
            field=models.UUIDField(default='cdb2dbb7-57b1-4d52-9a1d-a68ed72a7916', unique=True),
            preserve_default=False,
        ),
    ]
